services:
  backpack-server:
    image: 'backpack-ai-server:latest'
    privileged: true
    ports:
      - '8088:8089'
    environment:
      SPRING_AI_OPENAI_API_KEY: ${SPRING_AI_OPENAI_API_KEY} # https://docs.docker.com/compose/how-tos/environment-variables/variable-interpolation/