version: "3"

services:
  postgres-pgvector:
    image: pgvector/pgvector:0.7.4-pg17
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      interval: 5s
      retries: 5
      timeout: 2s
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "${EXPOSED_PORT}:5432"
    volumes:
      - ./postgres-extensions/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql
      - type: bind
        source: ${VOLUME}
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true