version: "3"

services:
  timescale:
    image: timescale/timescaledb:latest-pg16
    healthcheck:
      test: "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\""
      interval: 5s
      retries: 5
      timeout: 2s
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "${EXPOSED_PORT}:5432"
    volumes:
      - ./postgres-extensions/extensions.sql:/docker-entrypoint-initdb.d/extensions.sql
      - ./postgres-volume:/var/lib/postgresql/data
